package space.hypercode.core.utils;

/**
 * Static utility methods for argument validation.
 * <p>
 * Note: Methods are declared explicitly static (rather than relying on Lombok's
 * {@code @UtilityClass}) because AspectJ's post-compile weaving can overwrite
 * Lombok-generated bytecode modifications.
 */
public final class Preconditions {

    private Preconditions() {
        throw new UnsupportedOperationException("Utility class");
    }

    /**
     * Validates that the given object is not {@code null}.
     *
     * @param obj      the object to check
     * @param errorMsg the exception message if the check fails
     * @param <T>      the type of the object
     * @return {@code obj} if it is not null
     * @throws IllegalArgumentException if {@code obj} is null
     */
    public static <T> T validateNonNull(final T obj, final String errorMsg) {
        if (obj == null) {
            throw new IllegalArgumentException(errorMsg);
        }
        return obj;
    }

    /**
     * Validates that the given string is neither {@code null} nor empty.
     *
     * @param value    the string to check
     * @param errorMsg the exception message if the check fails
     * @return {@code value} if it is not null or empty
     * @throws IllegalArgumentException if {@code value} is null or empty
     */
    public static String validateNotNullOrEmpty(final String value, final String errorMsg) {
        if (value == null || value.isEmpty()) {
            throw new IllegalArgumentException(errorMsg);
        }
        return value;
    }
}
