package space.hypercode.core.utils;

/**
 * Static utility methods for argument validation.
 * <p>
 * Note: Methods are declared explicitly static (rather than relying on Lombok's
 * {@code @UtilityClass}) because AspectJ's post-compile weaving can overwrite
 * Lombok-generated bytecode modifications.
 */
public final class Preconditions {

    private Preconditions() {
        throw new UnsupportedOperationException("Utility class");
    }

    public static <T> T validateNonNull(final T obj, final String errorMsg) {
        if (obj == null) {
            throw new IllegalArgumentException(errorMsg);
        }
        return obj;
    }

    public static String validateNotNullOrEmpty(final String value, final String errorMsg) {
        if (value == null || value.isEmpty()) {
            throw new IllegalArgumentException(errorMsg);
        }
        return value;
    }
}
