package space.hypercode.core.configs;

import lombok.Builder;
import lombok.Getter;
import space.hypercode.core.converters.MemoizationKeyConverter;
import space.hypercode.core.eligibility.EligibilityCriteria;
import space.hypercode.core.eligibility.EligibilityCriterias;
import space.hypercode.core.eligibility.MemoizeAlways;

import java.time.Duration;
import java.util.Objects;

/**
 * Immutable configuration for a named memoization cache.
 * <p>
 * Note: Lombok annotations (Value/Builder) are not used here because AspectJ's
 * post-compile weaving overwrites Lombok-generated bytecode.
 */
@Getter
public final class MemoizationConfig {

    private final Duration ttl;
    private final long maxSize;
    private final MemoizationKeyConverter converter;
    private final EligibilityCriteria eligibilityCriteria;

    @Builder
    private MemoizationConfig(final Duration ttl,
                              final long maxSize,
                              final MemoizationKeyConverter converter,
                              final EligibilityCriteria eligibilityCriteria) {
        this.ttl = Objects.requireNonNull(ttl, "ttl must not be null");
        this.maxSize = maxSize;
        this.converter = Objects.requireNonNull(converter, "converter must not be null");
        this.eligibilityCriteria = eligibilityCriteria == null ? EligibilityCriterias.ALWAYS : eligibilityCriteria;
    }
}
