package space.hypercode.core.configs;

import space.hypercode.core.converters.MemoizationKeyConverter;

import java.time.Duration;
import java.util.Objects;

/**
 * Immutable configuration for a named memoization cache.
 * <p>
 * Note: Lombok annotations (Value/Builder) are not used here because AspectJ's
 * post-compile weaving overwrites Lombok-generated bytecode.
 */
public final class MemoizationConfig {

    private final Duration ttl;
    private final long maxSize;
    private final MemoizationKeyConverter converter;
    private final boolean cacheNulls;

    private MemoizationConfig(final Duration ttl,
                              final long maxSize,
                              final MemoizationKeyConverter converter,
                              final boolean cacheNulls) {
        this.ttl = Objects.requireNonNull(ttl, "ttl must not be null");
        this.maxSize = maxSize;
        this.converter = Objects.requireNonNull(converter, "converter must not be null");
        this.cacheNulls = cacheNulls;
    }

    public Duration getTtl() {
        return ttl;
    }

    public long getMaxSize() {
        return maxSize;
    }

    public MemoizationKeyConverter getConverter() {
        return converter;
    }

    public boolean isCacheNulls() {
        return cacheNulls;
    }

    public static MemoizationConfigBuilder builder() {
        return new MemoizationConfigBuilder();
    }

    public static final class MemoizationConfigBuilder {
        private Duration ttl;
        private long maxSize;
        private MemoizationKeyConverter converter;
        private boolean cacheNulls = true;

        private MemoizationConfigBuilder() {
        }

        public MemoizationConfigBuilder ttl(final Duration ttl) {
            this.ttl = ttl;
            return this;
        }

        public MemoizationConfigBuilder maxSize(final long maxSize) {
            this.maxSize = maxSize;
            return this;
        }

        public MemoizationConfigBuilder converter(final MemoizationKeyConverter converter) {
            this.converter = converter;
            return this;
        }

        public MemoizationConfigBuilder cacheNulls(final boolean cacheNulls) {
            this.cacheNulls = cacheNulls;
            return this;
        }

        public MemoizationConfig build() {
            return new MemoizationConfig(ttl, maxSize, converter, cacheNulls);
        }
    }
}
